-- PrepPilot core schema (SPEC.md: Data Model)
-- Written to run on Postgres and on H2 in PostgreSQL mode (used by the test suite).

CREATE TABLE users (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email         VARCHAR(255) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    created_at    TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE TABLE subscriptions (
    id                     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id                BIGINT NOT NULL UNIQUE REFERENCES users(id),
    tier                   VARCHAR(16) NOT NULL,            -- FREE | PAID
    status                 VARCHAR(32) NOT NULL,            -- ACTIVE | CANCELED | PAST_DUE | NONE
    stripe_customer_id     VARCHAR(255),
    stripe_subscription_id VARCHAR(255),
    renewed_at             TIMESTAMP WITH TIME ZONE
);

CREATE TABLE problems (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    slug       VARCHAR(100) NOT NULL UNIQUE,                -- keys coaching templates
    title      VARCHAR(200) NOT NULL,
    category   VARCHAR(32)  NOT NULL,                       -- ARRAYS | LINKED_LISTS | ...
    difficulty VARCHAR(16)  NOT NULL,                       -- EASY | MEDIUM | HARD | FAANG_BAR
    statement  VARCHAR(4000) NOT NULL
);

CREATE TABLE problem_progress (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id         BIGINT NOT NULL REFERENCES users(id),
    problem_id      BIGINT NOT NULL REFERENCES problems(id),
    difficulty      VARCHAR(16) NOT NULL,
    attempts        INTEGER NOT NULL DEFAULT 0,
    hints_used      INTEGER NOT NULL DEFAULT 0,
    status          VARCHAR(16) NOT NULL,                   -- IN_PROGRESS | SOLVED
    last_attempt_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uq_problem_progress UNIQUE (user_id, problem_id)
);

CREATE TABLE design_questions (
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    slug      VARCHAR(100) NOT NULL UNIQUE,
    title     VARCHAR(200) NOT NULL,
    category  VARCHAR(32)  NOT NULL,
    seniority VARCHAR(16)  NOT NULL,                        -- MID | SENIOR | STAFF
    prompt    VARCHAR(4000) NOT NULL
);

CREATE TABLE design_sessions (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id          BIGINT NOT NULL REFERENCES users(id),
    question_id      BIGINT NOT NULL REFERENCES design_questions(id),
    stage            VARCHAR(32) NOT NULL,                  -- REQUIREMENTS | COMPONENTS | DATA_MODEL | SCALING | COMPLETE
    transcript       VARCHAR(100000) NOT NULL,              -- JSON array of staged Q&A turns
    rubric_breakdown VARCHAR(4000),                         -- JSON, set on completion
    overall_score    INTEGER,
    started_at       TIMESTAMP WITH TIME ZONE NOT NULL,
    completed_at     TIMESTAMP WITH TIME ZONE
);

CREATE TABLE usage_counters (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id              BIGINT NOT NULL REFERENCES users(id),
    usage_date           DATE NOT NULL,
    dsa_sessions_used    INTEGER NOT NULL DEFAULT 0,
    design_sessions_used INTEGER NOT NULL DEFAULT 0,
    CONSTRAINT uq_usage_counters UNIQUE (user_id, usage_date)
);

CREATE INDEX idx_problem_progress_user ON problem_progress(user_id);
CREATE INDEX idx_design_sessions_user ON design_sessions(user_id);
CREATE INDEX idx_problems_category ON problems(category);
