-- Reduced starter bank: arrays + linked lists, EASY -> FAANG_BAR. Slugs key the coaching templates.
INSERT INTO problems (slug, title, category, difficulty, statement) VALUES
('two-sum', 'Two Sum', 'ARRAYS', 'EASY',
 'Given an array of integers nums and an integer target, return the indices of the two numbers that add up to target. Exactly one solution exists and you may not use the same element twice.'),
('best-time-to-buy-and-sell-stock', 'Best Time to Buy and Sell Stock', 'ARRAYS', 'EASY',
 'Given an array prices where prices[i] is the price of a stock on day i, choose one day to buy and a later day to sell to maximise profit. Return the maximum profit, or 0 if no profit is possible.'),
('contains-duplicate', 'Contains Duplicate', 'ARRAYS', 'EASY',
 'Given an integer array nums, return true if any value appears at least twice, and false if every element is distinct.'),
('maximum-subarray', 'Maximum Subarray', 'ARRAYS', 'MEDIUM',
 'Given an integer array nums, find the contiguous subarray with the largest sum and return that sum.'),
('product-of-array-except-self', 'Product of Array Except Self', 'ARRAYS', 'MEDIUM',
 'Given an integer array nums, return an array answer such that answer[i] equals the product of all elements of nums except nums[i]. Solve without division and in O(n) time.'),
('three-sum', '3Sum', 'ARRAYS', 'MEDIUM',
 'Given an integer array nums, return all unique triplets [a, b, c] such that a + b + c == 0. The solution set must not contain duplicate triplets.'),
('trapping-rain-water', 'Trapping Rain Water', 'ARRAYS', 'HARD',
 'Given n non-negative integers representing an elevation map where the width of each bar is 1, compute how much water it can trap after raining.'),
('sliding-window-maximum', 'Sliding Window Maximum', 'ARRAYS', 'FAANG_BAR',
 'Given an array nums and a window size k, return the maximum of each sliding window of size k as it moves from left to right. Aim for O(n).'),
('reverse-linked-list', 'Reverse Linked List', 'LINKED_LISTS', 'EASY',
 'Given the head of a singly linked list, reverse the list and return the new head.'),
('merge-two-sorted-lists', 'Merge Two Sorted Lists', 'LINKED_LISTS', 'EASY',
 'Merge two sorted linked lists into one sorted list by splicing together their nodes. Return the head of the merged list.'),
('linked-list-cycle', 'Linked List Cycle', 'LINKED_LISTS', 'EASY',
 'Given the head of a linked list, determine whether the list contains a cycle. Use O(1) extra memory.'),
('remove-nth-node-from-end', 'Remove Nth Node From End of List', 'LINKED_LISTS', 'MEDIUM',
 'Given the head of a linked list, remove the nth node from the end of the list and return its head. Try to do it in one pass.'),
('reorder-list', 'Reorder List', 'LINKED_LISTS', 'MEDIUM',
 'Given a singly linked list L0 -> L1 -> ... -> Ln, reorder it in place to L0 -> Ln -> L1 -> Ln-1 -> L2 -> ... without modifying node values.'),
('copy-list-with-random-pointer', 'Copy List with Random Pointer', 'LINKED_LISTS', 'HARD',
 'Each node of a linked list has a next pointer and a random pointer to any node in the list or null. Construct a deep copy of the list.'),
('merge-k-sorted-lists', 'Merge k Sorted Lists', 'LINKED_LISTS', 'FAANG_BAR',
 'You are given an array of k sorted linked lists. Merge all of them into one sorted linked list and return it. Analyse the time complexity of your approach.');
